% This test file was generated by Copilot. Validate the generated output before use.
classdef WeatherDataTest < matlab.unittest.TestCase
    properties
        weatherData
    end

    methods(TestMethodSetup)
        function setup(testCase)
            % Set up the import options and import the data
            opts = spreadsheetImportOptions("NumVariables", 12);
            opts.Sheet = "Sheet1";
            opts.DataRange = "A2:L243797";
            opts.VariableNames = ["Time", "state", "event_type", "damage_property", "damage_crops", "begin_lat", "begin_lon", "end_lat", "end_lon", "event_narrative", "storm_duration", "weathercats"];
            opts.VariableTypes = ["datetime", "categorical", "categorical", "categorical", "categorical", "string", "string", "string", "string", "string", "categorical", "categorical"];
            opts = setvaropts(opts, ["begin_lat", "begin_lon", "end_lat", "end_lon", "event_narrative"], "WhitespaceRule", "preserve");
            opts = setvaropts(opts, ["state", "event_type", "damage_property", "damage_crops", "begin_lat", "begin_lon", "end_lat", "end_lon", "event_narrative", "storm_duration", "weathercats"], "EmptyFieldRule", "auto");
            testCase.weatherData = readtable("C:\Users\Filip\Documents\Praca\Inne materiały\MATLAB Expo 2025\MATLAB_Expo\MATLAB_LTC\weatherData.xlsx", opts, "UseExcel", false);
        end
    end

    methods(Test)
        function testDamageTotalCalculation(testCase)
            % Test if damage_total is calculated correctly
            vars1 = ["damage_property", "damage_crops"];
            testCase.weatherData.damage_total = sum(testCase.weatherDataundefined, 2, 'omitnan');
            expectedTotal = testCase.weatherData.damage_property + testCase.weatherData.damage_crops;
            testCase.verifyEqual(testCase.weatherData.damage_total, expectedTotal, 'AbsTol', 1e-5);
        end

        function testMissingDataRemoval(testCase)
            % Test if missing data is removed correctly
            [cleanedData, missingIndices] = rmmissing(testCase.weatherData);
            testCase.verifyEqual(height(cleanedData) + nnz(missingIndices), height(testCase.weatherData));
        end

        function testOutlierFilling(testCase)
            % Test if outliers are filled correctly
            [newTable, outlierIndices, lo, hi] = filloutliers(testCase.weatherData, "linear", "movmedian", 2, ...
                DataVariables=["damage_property", "damage_crops", "begin_lat", "begin_lon", "damage_total"]);
            testCase.verifyEqual(height(newTable), height(testCase.weatherData), 'Outlier filling should not change the number of rows');
        end

        function testTopDamageRowsExtraction(testCase)
            % Test if the top 100 damage rows are extracted correctly
            [newTable, ~, ~, ~] = filloutliers(testCase.weatherData, "linear", "movmedian", 2, ...
                DataVariables=["damage_property", "damage_crops", "begin_lat", "begin_lon", "damage_total"]);
            topDamageRows = newTable(ismember(newTable.damage_total, maxk(newTable.damage_total, 100)), :);
            testCase.verifyEqual(height(topDamageRows), 100, 'Top damage rows should contain 100 entries');
        end
    end
end