% This test file was generated by Copilot. Validate the generated output before use.
classdef WeatherDataTest < matlab.unittest.TestCase
    properties
        weatherData
    end

    methods(TestMethodSetup)
        function setup(testCase)
            % Set up the import options and import the data
            opts = spreadsheetImportOptions("NumVariables", 12);
            opts.Sheet = "Sheet1";
            opts.DataRange = "A2:L243797";
            opts.VariableNames = ["Time", "state", "event_type", "damage_property", "damage_crops", "begin_lat", "begin_lon", "end_lat", "end_lon", "event_narrative", "storm_duration", "weathercats"];
            opts.VariableTypes = ["datetime", "categorical", "categorical", "categorical", "categorical", "string", "string", "string", "string", "string", "categorical", "categorical"];
            opts = setvaropts(opts, ["begin_lat", "begin_lon", "end_lat", "end_lon", "event_narrative"], "WhitespaceRule", "preserve");
            opts = setvaropts(opts, ["state", "event_type", "damage_property", "damage_crops", "begin_lat", "begin_lon", "end_lat", "end_lon", "event_narrative", "storm_duration", "weathercats"], "EmptyFieldRule", "auto");
            testCase.weatherData = readtable("C:\Users\Filip\Documents\Praca\Inne materiały\MATLAB Expo 2025\MATLAB_Expo\MATLAB_LTC\weatherData.xlsx", opts, "UseExcel", false);
        end
    end

    methods(Test)
        function testDamageTotalCalculation(testCase)
            % Test if damage_total is calculated correctly
            vars1 = ["damage_property", "damage_crops"];
            for i = 1:length(vars1)
                vname = vars1(i);
                testCase.weatherData.(vname) = string(testCase.weatherData.(vname));
                idxM = contains(testCase.weatherData.(vname), "M");
                testCase.weatherData.(vname) = erase(testCase.weatherData.(vname), ["K", "M"]);
                testCase.weatherData.(vname) = double(testCase.weatherData.(vname));
                testCase.weatherData.(vname)(idxM) = testCase.weatherData.(vname)(idxM) .* 1e3;
            end

            testCase.weatherData.damage_total = sum(testCase.weatherDataundefined, 2, 'omitnan');
            missingIdx = ismissing(testCase.weatherData.damage_property) & ismissing(testCase.weatherData.damage_crops);
            testCase.weatherData.damage_total(missingIdx) = NaN;

            % Verify that damage_total is correct
            testCase.verifyEqual(sum(testCase.weatherData.damage_total, 'omitnan'), ...
                sum(testCase.weatherData.damage_property, 'omitnan') + sum(testCase.weatherData.damage_crops, 'omitnan'));
        end

        function testCleanedDataRemoval(testCase)
            % Test if missing data is removed correctly
            [weatherData_cleaned, missingIndices] = rmmissing(testCase.weatherData);
            testCase.verifyEqual(height(weatherData_cleaned), height(testCase.weatherData) - nnz(missingIndices));
        end

        function testTopDamageRowsExtraction(testCase)
            % Test if the top 50 damage rows are extracted correctly
            [weatherData_cleaned, ~] = rmmissing(testCase.weatherData);
            topDamageRows = weatherData_cleaned(...
                ismember(weatherData_cleaned.damage_total, ...
                maxk(weatherData_cleaned.damage_total, 50)), :);
            testCase.verifyEqual(height(topDamageRows), 50);
        end
    end
end